export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
export const ADD_NEW_POST = "ADD_NEW_POST"
export const INCREMENT_VOTES = "INCREMENT_VOTES"
export const DECREASE_VOTES = "DECREASE_VOTES"

export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS"
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT"
